language: cpp
dist: xenial
sudo: required

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gfortran
        - gcc-8
        - gcc-8-multilib
        - g++-8
        - g++-8-multilib
       
env:
  global:
    - ALTERNATE_CC=gcc-8
    - ALTERNATE_CXX=g++-8
    - MAKE_THREADS=2
    
cache:
    directories:
     - OpenBLAS-0.3.4
     - dlib-19.16

before_install:
  - if [ ! -f "OpenBLAS-0.3.4/Makefile" ]; then wget https://github.com/xianyi/OpenBLAS/archive/v0.3.4.tar.gz; fi
  - if [ ! -f "OpenBLAS-0.3.4/Makefile" ]; then tar xf v0.3.4.tar.gz; fi

  - if [ ! -f "dlib-19.16/CMakeLists.txt" ]; then wget "https://github.com/davisking/dlib/archive/v19.16.tar.gz"; fi
  - if [ ! -f "dlib-19.16/CMakeLists.txt" ]; then tar xf v19.16.tar.gz; fi

install:
  - cd OpenBLAS-0.3.4
  - make FC=gfortran USE_THREAD=0 -j $MAKE_THREADS > /dev/null
  - sudo make PREFIX=/usr/local install
  - cd ..

  - mkdir -p dlib-19.16/build
  - cd dlib-19.16/build
  - cmake .. -DBUILD_SHARED_LIBS=ON -DDLIB_JPEG_SUPPORT=OFF -DDLIB_PNG_SUPPORT=OFF -DDLIB_NO_GUI_SUPPORT=ON
  - cmake --build . --config Release -- -j $MAKE_THREADS
  - sudo make install
  - sudo ldconfig
  - cd ../..
  
  - cp -r ./sampml/sampml ./examples/anti-aimbot/plugin/lib
  - cp -r ./dlib-19.16/dlib ./examples/anti-aimbot/plugin/lib
  
script:
  - cd examples/anti-aimbot/
  
  - echo "Building and testing training tools"
  - cd training
  - make  CXX=$ALTERNATE_CXX -j $MAKE_THREADS
  - time ./transformer
  - time ./analyzer
  - time ./svm
  - time ./rf
  - time ./dnn
  - time ./combined
  - time ./standalone_tester ./data/avoiding_detection.dat

  - pushd /$(pwd)
  - cd /usr/include
  - sudo ln -s asm-generic/ asm
  - popd

  - echo "Building plugin"
  - cd ../plugin
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$ALTERNATE_CC -DCMAKE_CXX_COMPILER=$ALTERNATE_CXX
  - cmake --build . -- -j $MAKE_THREADS
  
  - cd ../../../
